### PR TITLE
first pass at extracting plot components from ggplot2

### PR DESCRIPTION
**Pull request by schloerke**
not integrated, but the components and an example are there

### CODE REVIEW

**Comment by schloerke** [comment]
@hafen 

this produces three ggplot2 files for each plot here: https://github.com/hafen/trelliscopejs/pull/20/files#diff-4290d50c655295f940a6c2a47f1935ceR71

Let me know if there is anything else to add!

**Comment by schloerke** [comment]
files are currently saved in "_ignore/_pics/KEY.png" instead of a `tempfile()`.  This should be changed once the file height/widths/information is used in the browsers special "condensed" layout

**Comment by hafen** [comment]
Thanks! I'll take a look at it today.

Now I need to mess with the viewer to allow for this type of setup.

Also, this will be most useful if https://github.com/hafen/trelliscopejs/issues/4 was in place. I'm thinking it would be pretty easy for `facet_trelliscope()` but I haven't had a chance to work on it yet. We'd just have to make sure it's robust to different axis types (continuous, discrete, date).

**Comment by schloerke** [comment]
The  axis/label grabbing should handle continuous axis, discrete axis, facet_grid, top strips, and right strips.  I've used this in ggmatrix fairly successfully.  

The correct width conversion needs to be checked.  The test images appear to be correct, but it's difficult with the 'fac' variable and change of point size after extracting the pieces.  Don't know if we need to pass in a "extract and print" method.  If the point size was kept constant, this could be avoided.

**Pull request merged**
