### PR TITLE
added scale_*_date/time to possible scale types

### PR DESCRIPTION
**Pull request by schloerke**
Fixes issue #42 when dates are used on an axis

``` r
library(tidyverse)
#> Loading tidyverse: ggplot2
#> Loading tidyverse: tibble
#> Loading tidyverse: tidyr
#> Loading tidyverse: readr
#> Loading tidyverse: purrr
#> Loading tidyverse: dplyr
#> Conflicts with tidy packages ----------------------------------------------
#> filter(): dplyr, stats
#> lag():    dplyr, stats
library(trelliscopejs)
p <- economics_long[-(1:100), ] %>% ggplot(aes(date, value)) + geom_line()
p + facet_trelliscope(~variable, scales = "same", nrow = 2, ncol = 3, self_contained = TRUE)
#> using data from the first layer
```

``` r
p + facet_trelliscope(~variable, scales = "sliced", nrow = 2, ncol = 3, self_contained = TRUE)
#> using data from the first layer
```

``` r
p + facet_trelliscope(~variable, scales = "free", nrow = 2, ncol = 3, self_contained = TRUE)
#> using data from the first layer
```

### CODE REVIEW

**Comment by hafen** [comment]
Thanks @schloerke! Looks like I have some dplyr 0.7.0 stuff to fix too.

**Comment by hafen** [comment]
@schloerke, unrelated to dates, but related to axis scales, should an example like this work:

```r
qplot(class, cty, data = mpg, geom = c("boxplot", "jitter")) +
    facet_trelliscope(~ class, ncol = 7, height = 800, width = 200,
      state = list(sort = list(sort_spec("cty_mean"))), path = "_test",
      scales = c("free", "same"))
```

With this, I would expect the y axis limits to be the same, correct?

screen shot 2017-06-16 at 4 19 11 pm

**Comment by schloerke** [comment]
Correct! Because of how dates work, I might have to set the range value
manually.

I'll look later tonight

**Comment by hafen** [comment]
Cool thanks! I merged and did some stuff to make it work with dplyr 0.7 (really strange `unnest()` behavior).

**Pull request merged**
